runtime:
  mode: mock
  platform: win
  domain_id: 0
  qos_file: config/dds_qos.xml
  license_file: ""
  participant_name: cc_me_tracking_monitor_service

topics:
  task_update_topic:
    qos_profile: default_reliable
  preplan_result_topic:
    qos_profile: default_reliable
  manual_selection_request_topic:
    qos_profile: default_reliable
  manual_switch_request_topic:
    qos_profile: default_reliable
  electro_optical_linkage_cmd_topic:
    qos_profile: default_reliable
  stream_media_param_topic:
    qos_profile: default_reliable
  ownship_navigation_topic:
    qos_profile: default_reliable
  target_perception_topic:
    qos_profile: default_reliable
