runtime:
  mode: mock
  platform: win
  domain_id: "001"
  qos_file: config/dds_qos.xml
  license_file: ""
  participant_name: cc_cm_tracking_monitor_service

topics:
  cc_cm_tracking_monitor_service.v1.task_update_topic:
    qos_profile: default_reliable
  cc_cm_tracking_monitor_service.v1.preplan_result_topic:
    qos_profile: default_reliable
  cc_cm_tracking_monitor_service.v1.manual_selection_request_topic:
    qos_profile: default_reliable
  cc_cm_tracking_monitor_service.v1.manual_switch_request_topic:
    qos_profile: default_reliable
  cc_cm_tracking_monitor_service.v1.electro_optical_linkage_cmd_topic:
    qos_profile: default_reliable
  cc_cm_tracking_monitor_service.v1.stream_media_param_topic:
    qos_profile: default_reliable
  cc_cm_tracking_monitor_service.v1.ownship_navigation_topic:
    qos_profile: default_reliable
  cc_cm_tracking_monitor_service.v1.target_perception_topic:
    qos_profile: default_reliable
